### ISSUE TITLE
Error with end of the 4 digit in Square.

### ISSUE THREAD

**Issue by jitendra3109** [pcsaini/Hackathon#4]
As I played  game end of the 4 digit should be stop "With unfortunately stop ".

**Comment by Hrily** [comment]
Can I try and help?..

**Comment by Hrily** [comment]
I have fixed the issue.
Please review the pull request #8 ...

**Comment by Hrily** [comment]
@jsroyal 
Also please change the label `Hactoberfest` to `hacktoberfest` 
As the issue is not visible in the Hacktober issues list...

**Comment by jitendra3109** [comment]
Thank@Hrily to come with solution but I already  fix and it was small mistake.
