### ISSUE TITLE
Scratch a better UI design.

### ISSUE THREAD

**Issue by jitendra3109** [pcsaini/Hackathon#5]
Game idea is very good but sometime without interactive or creative make a boring game.But some time a small concept with great impact because of good UI or a better Animation.

**Comment by Hrily** [comment]
I would like to work upon it...

**Comment by jitendra3109** [comment]
Just like a Angry bird.

**Comment by Hrily** [comment]
I've made a PR #13...
Please review...

**Comment by jitendra3109** [comment]
Thanks @Hrily for show interest in UI.I would like to say something more interesting. Please go ahead  make like mario.
